-- drop table if exists cm.system__type__attribute cascade;
create table cm.system__type__attribute(
        id text not null,
        label text not null,
        definition text null,
        super_type_id text null,
        rdf_match text[] null,
	    constraint pk_system__type__attribute
	        primary key (id),
	    constraint fk_system__type__attribute__super_type
            foreign key (super_type_id) references cm.system__type__attribute(id)
            deferrable initially deferred
    );
alter table cm.system__type__attribute owner to edr_wheel;
grant select on table cm.system__type__attribute to edr_admin, edr_jwt, edr_edit, edr_read;
comment on table cm.system__type__attribute
    is 'Controlled list of system types (sub-types that the system depends on) for an attribute.';
comment on column cm.system__type__attribute.id
    is 'The system type id.';
comment on column cm.system__type__attribute.label
    is 'A human-friendly label for the system type.';
comment on column cm.system__type__attribute.definition
    is 'A brief definition of the system type. Content may be formatted using Markdown syntax.';
comment on column cm.system__type__attribute.super_type_id
    is 'The super (parent) system type id where a type specialises another.';
comment on column cm.system__type__attribute.rdf_match
    is 'The compact URIs of the well-known RDF resource the type matches, where applicable.';

-- initialise table
insert into cm.system__type__attribute (
	id,
    label,
	definition,
	super_type_id
)
values
	('edr-assertion', 'EDR Assertion', 'A simple attribute whose value is asserted - e.g. a name, identifier or description.', null),
    ('edr-observation', 'EDR Observation', 'An attribute whose value is estimated by observation: an event using some form of procedure (method). Values therefore have a describable quality/uncertainty and time.', null),
    ('edr-measurement', 'EDR Measurement', 'An attribute whose value is estimated by measurement (a subset of observations): an event using some form of sensor/instrument. Values are numeric and have a statistical quality/uncertainty. Values may be the instrument output - e.g. a spectra file.', 'edr-observation'),
    ('edr-prediction', 'EDR Prediction', 'An observation whose value is predicted by an algorithm that has processed one or more entity properties to estimate a new attribute. While predictions are be generated on demand, they may be stored to aid timely access to values that may be generated by long running processes.', 'edr-measurement')
on conflict (id) do update
    set
        label = excluded.label,
        definition = excluded.definition,
        super_type_id = excluded.super_type_id;